// Code generated by MockGen. DO NOT EDIT.
// Source: cw.go
//
// Generated by this command:
//
//	mockgen -source cw.go -destination=mocks/cw.go -package mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	cloudwatchlogs "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	gomock "go.uber.org/mock/gomock"
)

// MockCloudWatchClient is a mock of CloudWatchClient interface.
type MockCloudWatchClient struct {
	ctrl     *gomock.Controller
	recorder *MockCloudWatchClientMockRecorder
	isgomock struct{}
}

// MockCloudWatchClientMockRecorder is the mock recorder for MockCloudWatchClient.
type MockCloudWatchClientMockRecorder struct {
	mock *MockCloudWatchClient
}

// NewMockCloudWatchClient creates a new mock instance.
func NewMockCloudWatchClient(ctrl *gomock.Controller) *MockCloudWatchClient {
	mock := &MockCloudWatchClient{ctrl: ctrl}
	mock.recorder = &MockCloudWatchClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudWatchClient) EXPECT() *MockCloudWatchClientMockRecorder {
	return m.recorder
}

// DescribeLogGroups mocks base method.
func (m *MockCloudWatchClient) DescribeLogGroups(ctx context.Context, in *cloudwatchlogs.DescribeLogGroupsInput, opts ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DescribeLogGroups", varargs...)
	ret0, _ := ret[0].(*cloudwatchlogs.DescribeLogGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeLogGroups indicates an expected call of DescribeLogGroups.
func (mr *MockCloudWatchClientMockRecorder) DescribeLogGroups(ctx, in any, opts ...any) *MockCloudWatchClientDescribeLogGroupsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeLogGroups", reflect.TypeOf((*MockCloudWatchClient)(nil).DescribeLogGroups), varargs...)
	return &MockCloudWatchClientDescribeLogGroupsCall{Call: call}
}

// MockCloudWatchClientDescribeLogGroupsCall wrap *gomock.Call
type MockCloudWatchClientDescribeLogGroupsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCloudWatchClientDescribeLogGroupsCall) Return(arg0 *cloudwatchlogs.DescribeLogGroupsOutput, arg1 error) *MockCloudWatchClientDescribeLogGroupsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCloudWatchClientDescribeLogGroupsCall) Do(f func(context.Context, *cloudwatchlogs.DescribeLogGroupsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogGroupsOutput, error)) *MockCloudWatchClientDescribeLogGroupsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCloudWatchClientDescribeLogGroupsCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.DescribeLogGroupsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.DescribeLogGroupsOutput, error)) *MockCloudWatchClientDescribeLogGroupsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FilterLogEvents mocks base method.
func (m *MockCloudWatchClient) FilterLogEvents(ctx context.Context, in *cloudwatchlogs.FilterLogEventsInput, opts ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.FilterLogEventsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FilterLogEvents", varargs...)
	ret0, _ := ret[0].(*cloudwatchlogs.FilterLogEventsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterLogEvents indicates an expected call of FilterLogEvents.
func (mr *MockCloudWatchClientMockRecorder) FilterLogEvents(ctx, in any, opts ...any) *MockCloudWatchClientFilterLogEventsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterLogEvents", reflect.TypeOf((*MockCloudWatchClient)(nil).FilterLogEvents), varargs...)
	return &MockCloudWatchClientFilterLogEventsCall{Call: call}
}

// MockCloudWatchClientFilterLogEventsCall wrap *gomock.Call
type MockCloudWatchClientFilterLogEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCloudWatchClientFilterLogEventsCall) Return(arg0 *cloudwatchlogs.FilterLogEventsOutput, arg1 error) *MockCloudWatchClientFilterLogEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCloudWatchClientFilterLogEventsCall) Do(f func(context.Context, *cloudwatchlogs.FilterLogEventsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.FilterLogEventsOutput, error)) *MockCloudWatchClientFilterLogEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCloudWatchClientFilterLogEventsCall) DoAndReturn(f func(context.Context, *cloudwatchlogs.FilterLogEventsInput, ...func(*cloudwatchlogs.Options)) (*cloudwatchlogs.FilterLogEventsOutput, error)) *MockCloudWatchClientFilterLogEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
